openapi: "3.0.0"
info:
  title: eCommerce webSite API
  description: 'This is a event shop where people can buy ticket for artistic event where performer performs or seminar where artistic events are explanied'
  version: "1.0.0"
  contact:
    email: "leonardo.panizzo@mail.polimi.it"
servers:
  - description: Url where you can find our website
    url: https://bova-colombo-hyp2019.herokuapp.com/
tags:
  - name: "artisticEvent"
    description: "operation regarding the artistic events"
  - name: "performer"
    description: "operation regarding the performers"
  - name: "performs"
    description: "operation regarding who performs where"
  - name: "reservationArtisticEvent"
    description: "operation regarding the artistic events reserved by the users"
  - name: "reservationSeminar"
    description: "operation regarding the seminars reserved by the users"
  - name: "seminar"
    description: "operation regarding the seminars"
  - name: "users"
    description: "operations about signup/login/logout"
paths:
  /artisticEvent:
    get:
      tags:
      - artisticEvent
      summary: "artisticEvent available in the inventory"
      description: "List of all the artistic events in the inventory"
      operationId: getArtisticEvent
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/artisticEvent'
  /artisticEvent/types:
    get:
      tags:
      - artisticEvent
      summary: "available types of artistic events"
      description: "List of all the types of artistic event"
      operationId: getTypes
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                properties:
                  type:
                    type: string
                    format: character varying
  /artisticEvent/today:
    get:
      tags:
      - artisticEvent
      summary: "artistic events programmed for today"
      description: "list of all artistic events programmed for today"
      operationId: getArtisticEventToday
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/artisticEvent'
components:
  parameters:
    cookie:
      name: iduser
      in: cookie
      description: ""
      schema:
        type: string
  schemas:
    artisticEvent:
      type: object
      properties:
        idevent:
          type: integer
          format: integer
        title:
          type: string
          format: character varying
        description:
          type: string
          format: character varying
        place:
          type: string
          format: character varying
        type:
          type: string
          format: character varying
        dateAndTime:
          type: string
          format: timestamp without time zone
        idseminar:
          type: integer
          format: integer
      example:
        idevent: 1
        title: "Rock Show"
        description: "the x band will perform a rock show in y location"
        place: "Milan"
        type: "music"
        dateAndTime: "2019-09-21 15:30:00"
        idseminar: 4
    performer:
      type: object
      properties:
        idperformer:
          type: integer
          format: integer
        name:
          type: string
          format: character varying
        members:
          type: string
          format: character varying
        isgroup:
          type: boolean
          format: boolean
        affiliation:
          type: string
          format: character varying
        details:
          type: string
          format: character varying
        achievements:
          type: string
          format: character varying
        shortdescription:
          type: string
          format: character varying
      example:
        idperformer: 2
        name: "Against the Current"
        members: "Chrissy Costanza, Will Ferri, Dan Gow"
        isgroup: true
        affiliation: "Fueled by Ramen"
        details: "Against The Current (often abbreviated as ATC) is an American pop rock band based in Poughkeepsie, New York, and formed in 2011. More specifically, they play various variations of pop and rock, going from pure pop to pop punk and alternative rock. Against the Current was formed in early 2011 by Dan Gow, Will Ferri, and Jeremy Rompala and was later joined by Chrissy Costanza in the summer of 2011 after being introduced to Gow, Ferri, and Rompala through a mutual friend."
        achievements: ""
        shortdescription: "American rock pop band"
    performs:
      type: object
      properties:
        idperformer:
          type: integer
          format: integer
        idevent:
          type: integer
          format: integer
      example:
        idperformer: 3
        idevent: 2
    reservationArtisticEvent:
      type: object
      properties:
        iduser:
          type: integer
          format: integer
        idevent:
          type: integer
          format: integer
      example:
        iduser: 5
        idevent: 9
    reservationSeminar:
      type: object
      properties:
        iduser:
          type: integer
          format: integer
        idseminar:
          type: integer
          format: integer
      example:
        iduser: 5
        idseminar: 9
    seminar:
      type: object
      properties:
        idseminar:
          type: integer
          format: integer
        place:
          type: string
          format: character varying
        title:
          type: string
          format: character varying
        description:
          type: string
          format: character varying
        dateAndTime:
          type: string
          format: timestamp without time zone
      example:
        idseminar: 2
        place: "Via Vincenzo Monti 13, Milan"
        title: "The story of Orpheus and Eurydice"
        description: "What do we actually know about the ancient sotry of Orpheus and Eurydice? This seminar explores its deepest meanings, with a detailed analysis of different versions and what the same story impacted different generations in different historical and geopolitical contests."
        dateAndTime: "2019-09-05 20:00:00"
    users:
      type: object
      properties:
        iduser:
          type: integer
          format: integer
        mail:
          type: string
          format: character varying
        password:
          type: string
          format: character varying
        name:
          type: string
          format: character varying
  requestBodies:
    registrationForm: "A JSON object containing user information"
    required: true
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/users'
    logIn:
      description: "A JSON object containing information to login"
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              mail:
                type: string
                format: character varying
              pass:
                type: string
                format: character varying
